djangoProject/django_emploee/django_emploee/urls.py
from django.contrib import admin
from django.urls import path
from app01.views import depart,emp,nicenum,Admin,account,task

urlpatterns = [
   # path('admin/', admin.site.urls),
    #部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    path('depart/<int:nid>/edit/', depart.depart_edit),
    #员工管理
    path('user/list/', emp.user_list),
    path('user/add/', emp.user_add),
    path('user/modelform/add/', emp.user_modelform_add),
    path('user/<int:nid>/edit/', emp.emp_edit),
    #靓号管理
    path('nicenum/list/', nicenum.nicenum_list),
    path('nicenum/add/', nicenum.nicenum_add),
    path('nicenum/modelform/add/', nicenum.nicenum_modelform_add),
    path('nicenum/<int:nid>/edit/', nicenum.nicenum_edit),
    path('nicenum/<int:nid>/delete/', nicenum.nicenum_delete),
    #管理员管理
    path('admin/list/', Admin.admin_list),
    path('admin/add/', Admin.admin_add),
    path('admin/<int:nid>/reset/', Admin.admin_reset),
    #登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.img_code),
    #注册
    path('regist/', account.regist),
    #任务管理
    path('task/list/', task.task_list),
    path('task/add/', task.task_add),


]

djangoProject/django_emploee/app01/models.py
from django.db import models
# Create your models here.
class Department(models.Model):
    '''部门表'''
    dname = models.CharField(verbose_name='部门名称', max_length=32)

    def __str__(self):
        return self.dname

class emp(models.Model):
    name = models.CharField(verbose_name='员工姓名', max_length=32,)
    age = models.IntegerField(verbose_name='年龄')
    password = models.CharField(verbose_name='密码',max_length=32)
    account = models.DecimalField(verbose_name='账户余额', max_digits=10,decimal_places=2,default=0)
    hiretime = models.DateField(verbose_name='入职时间')
    gender_choice = ((1,'男'),(2,'女'))
    gender = models.SmallIntegerField(verbose_name='性别',choices=gender_choice)
    deptno = models.ForeignKey(verbose_name='部门',to='Department', to_field='id', on_delete=models.CASCADE)

class niceNum(models.Model):
    num = models.CharField(verbose_name='靓号',max_length=11)
    price = models.DecimalField(verbose_name='价格',max_digits=10,decimal_places=2)
    level_choice=((1,'普通靓号'),(2,'高级靓号'),(3,'极品靓号'))
    level = models.SmallIntegerField(verbose_name='靓号级别',choices=level_choice,default=1)
    status_choice=((1,'未占用'),(2,'已占用'))
    status = models.SmallIntegerField(verbose_name='状态',choices=status_choice,default=2)

class Admin(models.Model):
    username = models.CharField(verbose_name='用户名',max_length=32)
    password = models.CharField(verbose_name='密码',max_length=32)
    def __str__(self):
        return self.username
class Task(models.Model):
    level_choices = ((1,'紧急'),(2,'重要'),(3,'临时'))
    title = models.CharField(verbose_name='标题',max_length=64)
    detail = models.TextField(verbose_name='详细信息')
    level = models.SmallIntegerField(verbose_name='级别',choices=level_choices)
    user = models.ForeignKey(verbose_name='负责人',to='Admin',on_delete=models.CASCADE)

djangoProject/django_emploee/app01/views/Admin.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.Forms import AdminModelForm

def admin_list(request):
    obj = models.Admin.objects.all()
    form = AdminModelForm()
    contex = {
        'obj':obj,
        'form':form
    }
    return render(request,'admin_list.html',contex)

def admin_add(request):
    if request.method == 'GET':
        form = AdminModelForm()
        contex = {
            'title': '新建管理员',
            'form': form
        }
        return render(request, 'change.html', contex)
    elif request.method == 'POST':
        form = AdminModelForm(data=request.POST)
        contex = {
            'title': '新建管理员',
            'form': form
        }
        if form.is_valid():
            form.save()
            return redirect('/admin/list')
        return  render(request, 'change.html', contex)

def admin_reset(request,nid):
    obj = models.Admin.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = AdminModelForm(instance=obj)
        contex = {
            'title':'重置密码--{}'.format(obj.username),
            'form':form
        }
        return render(request,'change.html',contex)
    elif request.method == 'POST':
        form = AdminModelForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('/admin/list')
        contex = {
            'title':'重置密码--{}'.format(obj.username),
            'form':form
        }
        return render(request,'change.html',contex)

djangoProject/django_emploee/app01/views/account.py
from django.shortcuts import render, redirect,HttpResponse
from app01 import models
from app01.utils.Forms import loginModelForm
from app01.utils.code import check_code
from io import BytesIO
def login(request):
    if request.method == 'GET':
        form = loginModelForm()
        return render(request,'login.html',{'form':form})
    elif request.method == 'POST':
        form = loginModelForm(data=request.POST)
        if form.is_valid():
            # 先检查验证码
            input_code = form.cleaned_data.pop('code') #用pop，取得code后，还能把code从cleaned_data中删除，因为后面filter要用
            real_code = request.session.get('code') #生成验证码时存储在session中
            if input_code != real_code:
                form.add_error('code', '验证码错误')
                return render(request, 'login.html', {'form': form})
            #检查用户是否存在
            exit = models.Admin.objects.filter(**form.cleaned_data).first()
            if exit:
                #保存session
                request.session['info']={'username':exit.username,'id':exit.id}
                request.session.set_expiry(60*60*24)#设置有效期一天
                return redirect('/admin/list')
            else:
                form.add_error('password','用户名密码错误')
                return render(request, 'login.html', {'form': form})
        else:
            return render(request,'login.html',{'form':form})

def img_code(request):      #check_code()使用前要在项目文件中导入字体文件
    img,code = check_code() #借助这个函数生成（验证码图片，验证码字符串）
    stream = BytesIO() #借助这个对象，将图片存储到内存中
    img.save(stream,'png')
    request.session['code']=code #存储验证码，方便之后查找到并检验输入的是否正确
    request.session.set_expiry(60)#验证码60秒有效
    return HttpResponse(stream.getvalue())#给前端返回验证码图片

def logout(request):
    request.session.clear()
    return redirect('/login/')

def regist(request):
    if request.method == 'GET':
        form = loginModelForm()
        return render(request,'regist.html',{'form':form})
    elif request.method == 'POST':
        form = loginModelForm(data=request.POST)
        if form.is_valid():
            # 先检查验证码
            input_code = form.cleaned_data.pop('code')  # 用pop，取得code后，还能把code从cleaned_data中删除，因为后面filter要用
            real_code = request.session.get('code')  # 生成验证码时存储在session中
            if input_code != real_code:
                form.add_error('code', '验证码错误')
                return render(request, 'login.html', {'form': form})
            #检查用户是否存在
            print(form.cleaned_data)
            exit = models.Admin.objects.filter(username=form.cleaned_data['username']).first()
            if exit:
                form.add_error('username','用户名已存在')
                return render(request, 'login.html', {'form': form})
            else:
                models.Admin.objects.create(**form.cleaned_data)
                return HttpResponse('注册成功')

djangoProject/django_emploee/app01/views/depart.py
from django.shortcuts import render, HttpResponse, redirect
from app01 import models
def depart_list(request):
    dep_list = models.Department.objects.all()
    return render(request, 'depart_list.html', {'deplist': dep_list})

def depart_add(request):
    if request.method == 'GET':
        return render(request, 'depart_add.html')
    elif request.method == 'POST':
        dpname = request.POST.get('dname')
        models.Department.objects.create(dname=dpname)
        return redirect('/depart/list/')

def depart_delete(request):
    nid = request.GET.get('nid')
    models.Department.objects.filter(id=nid).delete()
    return redirect('/depart/list/')

def depart_edit(request, nid):
    if request.method == 'GET':
        dep_list = models.Department.objects.all()
        ed_dep = models.Department.objects.filter(id=nid).first()
        return render(request, 'depart_edit.html', {'edit': ed_dep, 'deplist': dep_list})
    elif request.method == 'POST':
        newdname = request.POST.get('dname')
        models.Department.objects.filter(id=nid).update(dname=newdname)
    return redirect('/depart/list/')

djangoProject/django_emploee/app01/views/emp.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.pagenation import Pagenation
from app01.utils.Forms import mymodel
def user_list(request):
    emp_list = models.emp.objects.all()
    obj = Pagenation(request,emp_list)
    return render(request, 'emp_list.html', {'emplist': obj.currentpage_data(),'page_str':obj.html()})

def user_add(request):
    if request.method == 'GET':
        contex = {
            'gdchoice': models.emp.gender_choice,
            'deplist': models.Department.objects.all()
        }
        return render(request, 'emp_add.html', contex)
    elif request.method == 'POST':
        name = request.POST.get('name')
        age = request.POST.get('age')
        pwd = request.POST.get('pwd')
        acount = request.POST.get('acount')
        hiretime = request.POST.get('hiretime')
        gender = request.POST.get('gender')
        dname = request.POST.get('dname')
        models.emp.objects.create(name=name, age=age, password=pwd, account=acount, hiretime=hiretime, gender=gender,
                                  deptno_id=dname)
        return redirect('/user/list/')

def user_modelform_add(request):
    if request.method == 'GET':
        form = mymodel()
        contex = {
            'title': '新建用户',
            'form': form
        }
        return render(request, 'change.html', contex)
    elif request.method == 'POST':
        form = mymodel(data=request.POST)
        contex = {
            'title': '新建用户',
            'form': form
        }
        if form.is_valid():
            form.save()
            return redirect('/user/list')
        else:
            return render(request, 'change.html', contex)

def emp_edit(request, nid):
    ed_obj = models.emp.objects.filter(id=nid).first()
    form = mymodel(instance=ed_obj)
    emplist = models.emp.objects.all()
    if request.method == 'GET':
        return render(request, 'emp_edit.html', {'emplist': emplist, 'nid': nid, 'md': form})
    elif request.method == 'POST':
        form = mymodel(data=request.POST, instance=ed_obj)
        if form.is_valid():
            form.save()
            return redirect('/user/list')
        else:
            return render(request, 'emp_edit.html', {'emplist': emplist, 'nid': nid, 'md': form})

djangoProject/django_emploee/app01/views/nicenum.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.pagenation import Pagenation
from app01.utils.Forms import nicenummodel,nicenumEditmodel

def nicenum_edit(request, nid):
    obj = models.niceNum.objects.filter(id=nid).first()
    nlist = models.niceNum.objects.all()
    if request.method == 'GET':
        form = nicenummodel(instance=obj)
        return render(request, 'nicenum_edit.html', {'form': form, 'numlist': nlist, 'nid': nid})
    elif request.method == 'POST':
        form = nicenumEditmodel(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('/nicenum/list')
        else:
            return render(request, 'nicenum_edit.html', {'form': form, 'numlist': nlist, 'nid': nid})

def nicenum_delete(request, nid):
    models.niceNum.objects.filter(id=nid).first().delete()
    return redirect('/nicenum/list/')

def nicenum_add(request):
    nlist = models.niceNum.objects.all()
    page_obj = Pagenation(request,nlist)
    form = nicenummodel()
    newid = 'new'
    if request.method == 'GET':
        return render(request, 'nicenum_add.html', {'nlist': page_obj.currentpage_data(), 'form': form, 'newid': newid})
    elif request.method == 'POST':
        form = nicenummodel(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/nicenum/list')
        else:
            return render(request, 'nicenum_add.html', {'nlist': nlist, 'form': form, 'newid': newid})

def nicenum_list(request):
    v = request.GET.get('search', '')
    serch_obj = models.niceNum.objects.filter(num__contains=v)
    page_obj = Pagenation(request,serch_obj)
    obj = page_obj.currentpage_data()

    return render(request, 'nicenum_list.html', {'nlist': obj, 'v': v,'page_li_str':page_obj.html()})

def nicenum_modelform_add(request):
    form = nicenummodel()
    if request.method == 'GET':
        context={
            'title':'新增靓号',
            'form':form
        }
        return render(request, 'change.html', context)
    elif request.method == 'POST':
        form = nicenummodel(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/nicenum/list')
        else:
            context = {
                'title': '新增靓号',
                'form': form
            }
            return render(request, 'change.html', context)

djangoProject/django_emploee/app01/views/task.py
from django.shortcuts import render, redirect,HttpResponse
from app01.utils.Forms import TaskModelForm
from django.views.decorators.csrf import csrf_exempt
import json
def task_list(request):
    form = TaskModelForm()
    return render(request,'task_list.html',{'form':form})

@csrf_exempt
def task_add(request):
    form = TaskModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        data_dict = {'status':True}
        return HttpResponse(json.dumps(data_dict))
    else:
        data_dict = {'status':False,'errors':form.errors}
        return HttpResponse(json.dumps(data_dict))

djangoProject/django_emploee/app01/templates/admin_list.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div style="margin-bottom: 10px">
        <a class="btn btn-primary " href="/admin/add/"> 新建管理员</a>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            管理员列表
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                {% for item in form %}
                <th>{{ item.label }}</th>
                {% endfor %}
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in obj %}
            <tr>
                <th scope="row">{{ item.id }}</th>
                <td>{{ item.username }}</td>
                <td>{{ item.password }}</td>
                <td>
                    <a class="btn btn-primary btn-xs" href="/admin/{{ item.id }}/reset"> 重置密码</a>
                    <a class="btn btn-danger btn-xs" href="#"> 删除</a>
                </td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>
{% endblock %}

djangoProject/django_emploee/app01/templates/change.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading">{{ title }}</div>
            <div class="panel-body">
                <form class="form-inline" method="post" novalidate>
                    {% csrf_token %}
                    {% for item in form %}
                        <div class="form" style="margin-bottom: 10px">
                            <div class="input-group">
                                <div class="input-group-addon "  >{{ item.label }}</div>
                                <div >{{ item }} <span style="color: orangered">{{ item.errors.0 }}</span></div>
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">保存</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

djangoProject/django_emploee/app01/templates/depart_edit.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
    <div style="margin-bottom: 10px">
        <a class="btn btn-primary " href="/depart/add/"> 新建部门</a>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            部门列表
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>部门名称</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for dep in deplist %}
                {% if dep.id == edit.id %}
                    <tr>
                        <form method="post">
                            <th scope="row">{{ dep.id }}</th>
                            <td>
                                {% csrf_token %}
                                <input type="text" value="{{ dep.dname }}" name="dname">
                            </td>
                            <td>
                                <button type="submit" class="btn btn-primary btn-xs"> 保存</button>
                                <a class="btn btn-danger btn-xs" href="/depart/delete/?nid={{ dep.id }}"> 删除</a>
                            </td>
                        </form>
                    </tr>
                {% else %}
                    <tr>
                        <th scope="row">{{ dep.id }}</th>
                        <td>{{ dep.dname }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/depart/{{ dep.id }}/edit"> 编辑</a>
                            <a class="btn btn-danger btn-xs" href="/depart/delete/?nid={{ dep.id }}"> 删除</a>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

djangoProject/django_emploee/app01/templates/emp_add.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading">新增员工</div>
            <div class="panel-body">
                <form class="form-inline" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">姓名</div>
                            <input type="text" class="form-control" name="name" placeholder="姓名">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">年龄</div>
                            <input type="text" class="form-control" name="age" placeholder="年龄">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">密码</div>
                            <input type="text" class="form-control" name="pwd" placeholder="密码">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">余额</div>
                            <input type="text" class="form-control" name="acount" placeholder="余额">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">入职日期</div>
                            <input type="text" class="form-control" name="hiretime" placeholder="入职日期">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">性别</div>
                            <select name="gender">
                                {% for gd in gdchoice %}
                                    <option  value="{{ gd.0 }}">{{ gd.1 }} </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">部门</div>
                            <select name="dname">
                                {% for dep in deplist %}
                                    <option  value="{{ dep.id }}">{{ dep.dname }} </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">保存</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

djangoProject/django_emploee/app01/templates/emp_edit.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-primary " href="/user/add/"> 新增员工</a>
            <a class="btn btn-primary " href="/user/modelform/add/"> 新增员工ModelForm</a>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                部门列表
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>年龄</th>
                    <th>密码</th>
                    <th>余额</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for emp in emplist %}
                    {% if emp.id == nid %}
                        <tr>
                            <th>{{ nid }}</th>
                            <form class="form-inline" method="post" novalidate>
                                {% csrf_token %}
                                {% for item in md %}
                                    <td>
                                        {{ item }}<span>{{ item.errors.0 }}</span>
                                    </td>
                                {% endfor %}
                                <td>
                                    <button type="submit" class="btn btn-success btn-xs">保存</button>
                                </td>
                            </form>
                        </tr>
                    {% else %}
                        <tr>
                            <th scope="row">{{ emp.id }}</th>
                            <td>{{ emp.name }}</td>
                            <td>{{ emp.age }}</td>
                            <td>{{ emp.password }}</td>
                            <td>{{ emp.account }}</td>
                            <td>{{ emp.hiretime|date:'Y-m-d' }}</td>
                            <td>{{ emp.get_gender_display }}</td>
                            <td>{{ emp.deptno.dname }}</td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="/user/{{ emp.id }}/edit"> 编辑</a>
                            </td>
                            <td>
                                <a class="btn btn-danger btn-xs" href="#"> 删除</a>
                            </td>

                        </tr>

                    {% endif %}

                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

djangoProject/django_emploee/app01/templates/emp_list.html
{% extends 'layout.html' %}

{% block content %}


    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-primary " href="/user/add/"> 新增员工</a>
            <a class="btn btn-primary " href="/user/modelform/add/"> 新增员工ModelForm</a>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                部门列表
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>年龄</th>
                    <th>密码</th>
                    <th>余额</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for emp in emplist %}
                    <tr>
                        <th scope="row">{{ emp.id }}</th>
                        <td>{{ emp.name }}</td>
                        <td>{{ emp.age }}</td>
                        <td>{{ emp.password }}</td>
                        <td>{{ emp.account }}</td>
                        <td>{{ emp.hiretime|date:'Y-m-d' }}</td>
                        <td>{{ emp.get_gender_display }}</td>
                        <td>{{ emp.deptno.dname }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/user/{{ emp.id }}/edit"> 编辑</a>
                            <a class="btn btn-danger btn-xs" href="#"> 删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <div>
            <ul class="pagination">
                {{ page_str }}
            </ul>
        </div>
    </div>



{% endblock %}

djangoProject/django_emploee/app01/templates/nicenum_edit.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">
        <div class="container">
            <a class="btn btn-primary " href="/nicenum/add/">新增靓号</a>
        </div>
        <div class="container">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">编辑靓号</div>

                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>靓号</th>
                        <th>价格</th>
                        <th>级别</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for num in numlist %}
                        {% if num.id == nid %}
                            <form method="post" novalidate>
                                {% csrf_token %}
                                <tr>
                                    <th>{{ nid }}</th>
                                    {% for item in form %}
                                        <td>{{ item }}<span class="btn-danger">{{ item.errors.0 }}</span></td>
                                    {% endfor %}
                                    <td>
                                        <button class="btn btn-xs btn-success" type="submit"> 保存</button>
                                        <a class="btn btn-xs btn-danger" href="/nicenum/list/"> 取消</a>
                                    </td>
                                </tr>
                            </form>
                        {% else %}
                            <tr>
                                <th scope="row">{{ num.id }}</th>
                                <td>{{ num.num }}</td>
                                <td>{{ num.price }}</td>
                                <td>{{ num.get_level_display }}</td>
                                <td>{{ num.get_status_display }}</td>
                                <td>
                                    <a class="btn btn-xs btn-primary" href="/nicenum/{{ num.id }}/edit">编辑</a>
                                    <a class="btn btn-xs btn-danger">删除</a>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}


                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}

djangoProject/django_emploee/app01/templates/nicenum_list.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">
        <div class="container clearfix">
            <a class="btn btn-primary " href="/nicenum/add/">新增靓号</a>
            <a class="btn btn-primary " href="/nicenum/modelform/add/">新增靓号ModelForm</a>
            <div style="float: right ;width: 300px">
                <form method="get">
                    <div class="input-group ">
                        <input style="width: 200px" type="text" name="search" value="{{ v }}" class="form-control"
                               placeholder="查询靓号">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="container">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">靓号列表</div>

                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>靓号</th>
                        <th>价格</th>
                        <th>级别</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for num in nlist %}
                        <tr>
                            <th scope="row">{{ num.id }}</th>
                            <td>{{ num.num }}</td>
                            <td>{{ num.price }}</td>
                            <td>{{ num.get_level_display }}</td>
                            <td>{{ num.get_status_display }}</td>
                            <td>
                                <a class="btn btn-xs btn-primary" href="/nicenum/{{ num.id }}/edit">编辑</a>
                                <a class="btn btn-xs btn-danger" href="/nicenum/{{ num.id }}/delete">删除</a>
                            </td>
                        </tr>
                    {% endfor %}

                    {% block add %}
                    {% endblock %}

                    </tbody>
                </table>
            </div>
        </div>

        <div>
            <ul class="pagination">
                {{ page_li_str }}
            </ul>
        </div>
    </div>

{% endblock %}